### ISSUE TITLE
Missing dependency in installation instructions

### ISSUE THREAD

**Issue by xylophoneengine** [eMoflon/emoflon-ibex-tutorial#1]
When following the instructions to install emoflon ibex the following error occurs
![Capture](https://user-images.githubusercontent.com/74956800/136651160-4d0224d2-dc34-4840-bd21-e2629adc579d.PNG)
:
![error](https://user-images.githubusercontent.com/74956800/136651162-f109e274-915f-47c9-8712-0026ef9b98b2.PNG)
I was able to resolve this problem by installing HiPe (https://hipe-devops.github.io/HiPE-Updatesite/hipe.updatesite/).

I think the instructions should be updated or the published packages revised if this behaviour is not expected.

**Comment by maxkratz** [comment]
This was already fixed in the tutorial + the installation steps in [the eMoflon::IBeX repository](https://github.com/eMoflon/emoflon-ibex).
