### ISSUE TITLE
Installation of GraphViz, missing installation instructions

### ISSUE THREAD

**Issue by xylophoneengine** [eMoflon/emoflon-ibex-tutorial#2]
Is it possible to check if newer versions of GraphViz are now compatible or give a detailed installation instructions for it?
The tutorial seems to use Eclipse on Windows 10, however, GraphViz 2.38 installers are not available anymore and the given installation instructions are written for Linux from Scratch.
Best regards ~

**Comment by maxkratz** [comment]
This was already fixed in later versions of the tutorial.
