### ISSUE TITLE
Missing "findRoomWithoutNurse" pattern in Ecore+GTEmpty/emoflon-ibex-tutorial/HospitalTransformRules/src/HospitalTransformRules/Rules.gt

### ISSUE THREAD

**Issue by xylophoneengine** [eMoflon/emoflon-ibex-tutorial#3]
Hello,

The file [Rules.gt](https://github.com/eMoflon/emoflon-ibex-tutorial/blob/516eaa92f524c5909a0df0d2a4d8dc9bbe986da3/HospitalTransformRules/src/HospitalTransformRules/Rules.gt) is lacking the "findRoomWithoutNurse" which is needed by [HospitalRules.java](https://github.com/eMoflon/emoflon-ibex-tutorial/blob/516eaa92f524c5909a0df0d2a4d8dc9bbe986da3/HospitalTransformRules/src/HospitalTransformRules/HospitalRules.java).
The master branch does have the pattern included. Thus either tutorial chapters 2.3 to 2.6 are incomplete or pattern was not committed.

Best regards

**Comment by maxkratz** [comment]
In the current version, said rule is included.
